        // js/script.js

        // Массив товаров (скопирован из вашего сообщения)
        // PRODUCTS_START
const products = [
  { name: "Абажур \"Волна\" угловой, липа, 27*10,5*30,5см \"Банные штучки\"/3, шт", price: 456.8, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Автоклав 27 л Беларусский с биметрическим термометром, шт", price: 6615.0, stock: 5.0, volume: "27 л", category: "home", diameter: "" },
  { name: "Автоклав 33 л Беларусский с биметрическим термометром, шт", price: 7927.5, stock: 7.0, volume: "33 л", category: "home", diameter: "" },
  { name: "Автостеклоочиститель зимний \"POLAR BEAR\" (-15 С) 4л ПЭТ, шт", price: 199.5, stock: 107.0, volume: "4 л", category: "home", diameter: "" },
  { name: "Автостеклоочиститель зимний \"POLAR BEAR\" (-20 С) 4 литра, шт", price: 304.5, stock: 29.0, volume: "4 л", category: "home", diameter: "" },
  { name: "АГРО 160 чёрный, ширина 1,6м/120 п.м, м", price: 89.3, stock: 58.5, volume: "---", category: "agriculture", diameter: "" },
  { name: "АГРОтекстиль  60\" белый 3,2/150м, м", price: 63.0, stock: 167.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "АГРОтекстиль 100\" белый 3,20 Тула/100м, м", price: 105.0, stock: 39.7, volume: "---", category: "agriculture", diameter: "" },
  { name: "АГРОтекстиль 100\" чёрный 3,20 Тула/100м, м", price: 115.5, stock: 16.4, volume: "---", category: "agriculture", diameter: "" },
  { name: "Ареометр АСП-3 70-100 ГОСТ, шт", price: 204.8, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Ареометр-сахаромер 0-25 ГОСТ, шт", price: 210.0, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Армированная плёнка 200 г/м2 (2м*25 п.м.) с леской, пог. м", price: 195.0, stock: 50.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Бак 110 л. оцинкованный с крышкой/3, шт", price: 2625.0, stock: 1.0, volume: "110 л", category: "lids", diameter: "" },
  { name: "Бак 32 л. оцинкованный с крышкой и краном , шт", price: 1155.0, stock: 1.0, volume: "32 л", category: "lids", diameter: "" },
  { name: "Бак 32 л. оцинкованный с крышкой/5, шт", price: 1050.0, stock: 2.0, volume: "32 л", category: "lids", diameter: "" },
  { name: "Бак 80 л. оцинкованный с крышкой/3, шт", price: 2257.5, stock: 4.0, volume: "80 л", category: "lids", diameter: "" },
  { name: "Бак для мусора 65 литров на колёсах Эконом, шт", price: 1522.5, stock: 1.0, volume: "65 л", category: "containers", diameter: "" },
  { name: "Бак хозяйственный 100л/5, шт", price: 1417.5, stock: 8.0, volume: "100 л", category: "containers", diameter: "" },
  { name: "Бак хозяйственный 120л/5, шт", price: 1575.0, stock: 2.0, volume: "120 л", category: "containers", diameter: "" },
  { name: "Банка  3,8 л стеклянная \"кольцо\"/6, шт", price: 735.0, stock: 3.0, volume: "3.8 л", category: "banks", diameter: "" },
  { name: "Банка  7 л. \"Ламели\"  СКО  проз., шт", price: 945.0, stock: 1.0, volume: "7 л", category: "banks", diameter: "" },
  { name: "Банка  9 л. стеклянная с гидрозатвором/2, шт", price: 1207.5, stock: 1.0, volume: "9 л", category: "banks", diameter: "" },
  { name: "Банка 0,020 л. d43/72, шт", price: 14.2, stock: 4136.0, volume: "0.020 л", category: "banks", diameter: "d43" },
  { name: "Банка 0,030 л. d43/72, шт", price: 17.3, stock: 3112.0, volume: "0.030 л", category: "banks", diameter: "d43" },
  { name: "Банка 0,045 л. Шестигранник d43/38, шт", price: 16.3, stock: 2549.0, volume: "0.045 л", category: "banks", diameter: "d43" },
  { name: "Банка 0,050 л. d58/22, шт", price: 17.0, stock: 3864.0, volume: "0.050 л", category: "banks", diameter: "d58" },
  { name: "Банка 0,100 л с корковой пробкой, шт", price: 120.8, stock: 76.0, volume: "0.100 л", category: "banks", diameter: "" },
  { name: "Банка 0,100 л. Икра d66/17, шт", price: 20.5, stock: 11213.0, volume: "0.100 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,100 л. Сота d58/22, шт", price: 20.0, stock: 9929.0, volume: "0.100 л", category: "banks", diameter: "d58" },
  { name: "Банка 0,105 л. d63/36, шт", price: 10.5, stock: 481.0, volume: "0.105 л", category: "banks", diameter: "d63" },
  { name: "Банка 0,120 л. Солонка d48/26, шт", price: 12.1, stock: 1601.0, volume: "0.120 л", category: "banks", diameter: "d48" },
  { name: "Банка 0,120 л. Солонка. d48/50 пакет, шт", price: 12.1, stock: 6000.0, volume: "0.120 л", category: "banks", diameter: "d48" },
  { name: "Банка 0,130 л. Цветочек d66/18, шт", price: 15.8, stock: 1160.0, volume: "0.130 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,200 л. Аврора d66/17, шт", price: 15.0, stock: 10095.0, volume: "0.200 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,200 л. Глория d66/24шт.уп, шт", price: 18.9, stock: 824.0, volume: "0.200 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,200 л. Горчичка КБ-13 d58/22, шт", price: 14.5, stock: 5391.0, volume: "0.200 л", category: "banks", diameter: "d58" },
  { name: "Банка 0,200 л. Сота К-194. d58/22, шт", price: 23.0, stock: 2970.0, volume: "0.200 л", category: "banks", diameter: "d58" },
  { name: "Банка 0,230 л. Лампочка d58/14, шт", price: 23.1, stock: 227.0, volume: "0.230 л", category: "banks", diameter: "d58" },
  { name: "Банка 0,250 л. КБ-149 d66/4400/40 пакет, шт", price: 16.3, stock: 2471.0, volume: "0.250 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,250 л. Кубик. КБ152. d66/4800/40 пакет, шт", price: 16.8, stock: 1179.0, volume: "0.250 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,250 л. Шайба ТО d82 /4752/14шт. уп, шт", price: 18.5, stock: 9759.0, volume: "0.250 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,250 л. Шестигранник d82/14, шт", price: 16.8, stock: 675.0, volume: "0.250 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,255 л. d66/18, шт", price: 15.2, stock: 7576.0, volume: "0.255 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,260 л. Мёд d63/12, шт", price: 25.2, stock: 2927.0, volume: "0.260 л", category: "banks", diameter: "d63" },
  { name: "Банка 0,275 л. К-275 \"Мишка\"/ d58/14, шт", price: 27.3, stock: 699.0, volume: "0.275 л", category: "banks", diameter: "d58" },
  { name: "Банка 0,280 л. Октава d66/18, шт", price: 20.5, stock: 287.0, volume: "0.280 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,330 л. К-665, d66/14, шт", price: 20.0, stock: 137.0, volume: "0.330 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,350 л. Туба. d66/18, шт", price: 16.5, stock: 3510.0, volume: "0.350 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,350 л. Шайба КБ-212 d82/3312/24 пакет, шт", price: 23.1, stock: 20812.0, volume: "0.350 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,360 л.ТО-82  Шестигранник d82/11, шт", price: 26.8, stock: 704.0, volume: "0.360 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,390 л. Кубик. КБ 140 d82/3360/28 пакет, шт", price: 23.6, stock: 8499.0, volume: "0.390 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,450 л. Кубышка d82/11, шт", price: 18.4, stock: 1854.0, volume: "0.450 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,5 л с крышкой п/э \"Медовая\"/21, шт", price: 78.8, stock: 7.0, volume: "0.5 л", category: "banks", diameter: "" },
  { name: "Банка 0,500 л. (К) d82 /2160/20, шт", price: 18.0, stock: 14477.0, volume: "0.500 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,500 л. Бочонок КБ94 d82/2280/24/12 пакет, шт", price: 22.6, stock: 3977.0, volume: "0.500 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,500 л. Груша d82/11, шт", price: 24.2, stock: 1305.0, volume: "0.500 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,500 л. Овал. К-667 d82/11, шт", price: 22.1, stock: 803.0, volume: "0.500 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,500 л. Фрутоняня. Арт. КБ 70. d66/2600/40 пакет, шт", price: 22.6, stock: 4926.0, volume: "0.500 л", category: "banks", diameter: "d66" },
  { name: "Банка 0,650 л. Глория d82/12, шт", price: 33.0, stock: 1188.0, volume: "0.650 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,7 л с крышкой п/э \"Медовая\"/21, шт", price: 84.0, stock: 17.0, volume: "0.7 л", category: "banks", diameter: "" },
  { name: "Банка 0,720 л. (К) d82/16, шт", price: 21.0, stock: 336.0, volume: "0.720 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,720 л. d82/11, шт", price: 23.0, stock: 4790.0, volume: "0.720 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,720 л. Кубышка. А141. d-82/12, шт", price: 30.0, stock: 480.0, volume: "0.720 л", category: "banks", diameter: "" },
  { name: "Банка 0,75 с крышкой п/э/50, шт", price: 42.0, stock: 26.0, volume: "---", category: "banks", diameter: "" },
  { name: "Банка 0,800 л. Арт. 2Т. d82/12, шт", price: 33.1, stock: 103.0, volume: "0.800 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,950 л. (К) d82/1440/12, шт", price: 29.4, stock: 8611.0, volume: "0.950 л", category: "banks", diameter: "d82" },
  { name: "Банка 0,950 л. Арт.КБ 80. d100/1400/20 пакет, шт", price: 38.9, stock: 1916.0, volume: "0.950 л", category: "banks", diameter: "d100" },
  { name: "Банка 0,950 л. Сезон d82/1452/11, шт", price: 29.4, stock: 73.0, volume: "0.950 л", category: "banks", diameter: "d82" },
  { name: "Банка 1 л. п/э с крышкой/40, шт", price: 47.3, stock: 1.0, volume: "1 л", category: "banks", diameter: "" },
  { name: "Банка 1,5 л. Арт. КБ 79. d100/810/15 пакет, шт", price: 55.7, stock: 2402.0, volume: "1.5 л", category: "banks", diameter: "d100" },
  { name: "Банка 1,5 л. Дагестан d82/12, шт", price: 50.4, stock: 182.0, volume: "1.5 л", category: "banks", diameter: "d82" },
  { name: "Банка 1,5 л. Кубышка d82/9, шт", price: 54.1, stock: 158.0, volume: "1.5 л", category: "banks", diameter: "d82" },
  { name: "Банка 1,5 л. Фонарь А118. d100/780/6 пакет, шт", price: 51.5, stock: 383.0, volume: "1.5 л", category: "banks", diameter: "d100" },
  { name: "Банка 16 л. стеклянная с ручкой (фиолет. с клапаном) /4 шт уп, шт", price: 1365.0, stock: 3.0, volume: "16 л", category: "banks", diameter: "" },
  { name: "Банка 18 л. стеклянная с гидрозатвором /4шт.уп, шт", price: 1995.0, stock: 7.0, volume: "18 л", category: "banks", diameter: "" },
  { name: "Банка 2 л. Экран. d82/6, шт", price: 54.1, stock: 1050.0, volume: "2 л", category: "banks", diameter: "d82" },
  { name: "Банка 20л. стеклянная с ручкой (фиолет. с клапаном) /4 шт уп, шт", price: 1900.0, stock: 2.0, volume: "20 л", category: "banks", diameter: "" },
  { name: "Банка 25 л. стеклянная с гидрозатвором/2шт.уп, шт", price: 2793.0, stock: 6.0, volume: "25 л", category: "banks", diameter: "" },
  { name: "Банка 3 л. КБ2 d100/4, шт", price: 83.0, stock: 216.0, volume: "3 л", category: "banks", diameter: "d100" },
  { name: "Банка 3 л. Экран. d82/6   , шт", price: 70.9, stock: 200.0, volume: "3 л", category: "banks", diameter: "d82" },
  { name: "Банка 3,1 л. КБ249 d100/12 пакет, шт", price: 76.7, stock: 95.0, volume: "3.1 л", category: "banks", diameter: "d100" },
  { name: "Банка 5 л. d110 с крышкой и ручкой/4, шт", price: 200.0, stock: 3.0, volume: "5 л", category: "banks", diameter: "d110" },
  { name: "Банка 5 л. с крышкой и ручкой (мерная) d110/4шт.уп, шт", price: 250.0, stock: 40.0, volume: "5 л", category: "banks", diameter: "d110" },
  { name: "Банка с крышкой (стекло) 0,110 мл, шт", price: 115.5, stock: 59.0, volume: "0.110 мл", category: "banks", diameter: "" },
  { name: "Банка с крышкой (стекло) 0,25 л/ прокладка прозрачная, шт", price: 141.8, stock: 56.0, volume: "0.25 л", category: "banks", diameter: "" },
  { name: "Банка с крышкой (стекло) 0,5 л/ уплотнитель прозрачный , шт", price: 136.5, stock: 313.0, volume: "0.5 л", category: "banks", diameter: "" },
  { name: "Банка с крышкой (стекло) 0,65 л/ уплотнитель прозрачный , шт", price: 141.8, stock: 97.0, volume: "0.65 л", category: "banks", diameter: "" },
  { name: "Банка с крышкой (стекло) 0,8 л/уплотнитель прозрачный, шт", price: 162.8, stock: 154.0, volume: "0.8 л", category: "banks", diameter: "" },
  { name: "Банка СКО 0,500 л. d82/3024/28 пакет, шт", price: 23.0, stock: 11720.0, volume: "0.500 л", category: "banks", diameter: "d82" },
  { name: "Банка СКО 0,650 л. d82/2100/28 пакет, шт", price: 24.2, stock: 911.0, volume: "0.650 л", category: "banks", diameter: "d82" },
  { name: "Банка СКО 0,950 л. d82/12шт.уп, шт", price: 32.0, stock: 1488.0, volume: "0.950 л", category: "banks", diameter: "d82" },
  { name: "Банка СКО 1,5 л. d82/12 пакет, шт", price: 61.4, stock: 408.0, volume: "1.5 л", category: "banks", diameter: "d82" },
  { name: "Банка СКО 1,5 л. d82/900/15 пакет, шт", price: 50.9, stock: 160.0, volume: "1.5 л", category: "banks", diameter: "d82" },
  { name: "Банка СКО 2 л. d82/720/6 пакет, шт", price: 69.3, stock: 449.0, volume: "2 л", category: "banks", diameter: "d82" },
  { name: "Беседка \"Кекс\" (каркас 2,1*2,6**2,10)  (кв.труба 25*25), шт", price: 14700.0, stock: 10.0, volume: "---", category: "home", diameter: "" },
  { name: "Беседка \"Уют\" (каркас 2,1*2,4**2,15) 50 кг доски отдельно, шт", price: 14175.0, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Бочка -бак 300 л квадратная без крышки/3, шт", price: 4462.5, stock: 1.0, volume: "300 л", category: "lids", diameter: "" },
  { name: "Бочка 120 л с метал. ободом, шт", price: 2700.0, stock: 3.0, volume: "120 л", category: "containers", diameter: "" },
  { name: "Бочка 20 дм3 с метал. ободом, шт", price: 1155.0, stock: 1.0, volume: "---", category: "containers", diameter: "" },
  { name: "Бочка 227 л с крышкой под шланг , шт", price: 3307.5, stock: 1.0, volume: "227 л", category: "lids", diameter: "" },
  { name: "Бочка 230 л без крышки/барабан, шт", price: 3000.0, stock: 2.0, volume: "230 л", category: "lids", diameter: "" },
  { name: "Бочка 40 л круглая, шт", price: 1102.5, stock: 2.0, volume: "40 л", category: "containers", diameter: "" },
  { name: "Бугельная пробка /пр-во Россия/1000, шт", price: 25.2, stock: 786.0, volume: "---", category: "home", diameter: "" },
  { name: "Бутылка 0,050 л. d18/115/107, шт", price: 16.3, stock: 1348.0, volume: "0.050 л", category: "bottles", diameter: "d18" },
  { name: "Бутылка 0,050 л. Futuro d18/80, шт", price: 15.8, stock: 426.0, volume: "0.050 л", category: "bottles", diameter: "d18" },
  { name: "Бутылка 0,100 л. d28/70, шт", price: 18.5, stock: 799.0, volume: "0.100 л", category: "bottles", diameter: "d28" },
  { name: "Бутылка 0,100 л. Пляшка d28/44, шт", price: 15.2, stock: 7077.0, volume: "0.100 л", category: "bottles", diameter: "d28" },
  { name: "Бутылка 0,250 л. Арт. В-28. коричневая/24, шт", price: 18.4, stock: 234.0, volume: "0.250 л", category: "bottles", diameter: "" },
  { name: "Бутылка 0,250 л. Гаврош d28/23, шт", price: 17.3, stock: 1120.0, volume: "0.250 л", category: "bottles", diameter: "d28" },
  { name: "Бутылка 0,250 л. для масла \"Олива\" цв.коричневый/35, шт", price: 31.0, stock: 347.0, volume: "0.250 л", category: "bottles", diameter: "" },
  { name: "Бутылка 0,250 л. Сок d43/22, шт", price: 14.5, stock: 233.0, volume: "0.250 л", category: "bottles", diameter: "d43" },
  { name: "Бутылка 0,250 л. Фляжка г.Коркино d28/24шт.уп, шт", price: 26.0, stock: 2312.0, volume: "0.250 л", category: "bottles", diameter: "d28" },
  { name: "Бутылка 0,310 л. КБ 38 d43/22/40шт.уп, шт", price: 19.4, stock: 784.0, volume: "0.310 л", category: "bottles", diameter: "d43" },
  { name: "Бутылка 0,500 л К 37/18шт. уп/новая, шт", price: 29.4, stock: 3.0, volume: "0.500 л", category: "bottles", diameter: "" },
  { name: "Бутылка 0,500 л. Арт. К-640. Молочная d43/15, шт", price: 21.0, stock: 390.0, volume: "0.500 л", category: "bottles", diameter: "d43" },
  { name: "Бутылка 0,500 л. Базис 2. КПМ3. Гуала/15, шт", price: 21.5, stock: 2366.0, volume: "0.500 л", category: "bottles", diameter: "" },
  { name: "Бутылка 0,500 л. Бугельная Beer LM коричневая (пробка отдельно)/15, шт", price: 47.8, stock: 219.0, volume: "0.500 л", category: "bottles", diameter: "" },
  { name: "Бутылка 0,500 л. Бугельная бесцветная (пробка отдельно)/15, шт", price: 47.8, stock: 308.0, volume: "0.500 л", category: "bottles", diameter: "" },
  { name: "Бутылка 0,500 л. Забава d28/15, шт", price: 20.0, stock: 2908.0, volume: "0.500 л", category: "bottles", diameter: "d28" },
  { name: "Бутылка 0,500 л. Камю. Арт. П-30/12, шт", price: 46.0, stock: 301.0, volume: "0.500 л", category: "bottles", diameter: "" },
  { name: "Бутылка 0,700 л. Камю. Арт. П-30/12, шт", price: 57.8, stock: 526.0, volume: "0.700 л", category: "bottles", diameter: "" },
  { name: "Бутылка 0,750 л. Бугельная Bordo classic LM виноградная (пробка отдельно)/12, шт", price: 53.6, stock: 378.0, volume: "0.750 л", category: "bottles", diameter: "" },
  { name: "Бутылка 1 литр. Бугельная бесцветная П-32-10-1000 (пробка отдельно)/9, шт", price: 89.3, stock: 295.0, volume: "1 л", category: "bottles", diameter: "" },
  { name: "Бутылка 1 литр. Бугельная коричневая Litva 2 (пробка отдельно)/12, шт", price: 84.0, stock: 7.0, volume: "1 л", category: "bottles", diameter: "" },
  { name: "Бутылка 1 литр. Бугельная коричневая П-32 (пробка отдельно)/9, шт", price: 89.3, stock: 364.0, volume: "1 л", category: "bottles", diameter: "" },
  { name: "Бутылка 1 литр. Винная WINE1 d66/8шт.уп, шт", price: 31.0, stock: 397.0, volume: "1 л", category: "bottles", diameter: "d66" },
  { name: "Бутылка 1,5 л. \"Традиция\" бронза, шт", price: 472.5, stock: 5.0, volume: "1.5 л", category: "bottles", diameter: "" },
  { name: "Бутылка 12 л. \"GARRAFA CABERNET\" с пробкой, шт", price: 3675.0, stock: 5.0, volume: "12 л", category: "bottles", diameter: "" },
  { name: "Бутылка 12 л. \"GARRAFA COLONIAL\" с пробкой, шт", price: 3675.0, stock: 5.0, volume: "12 л", category: "bottles", diameter: "" },
  { name: "Бутылка 2 литра. Бугельная Most LM бесцветная (пробка отдельно)/24, шт", price: 283.5, stock: 6.0, volume: "2 л", category: "bottles", diameter: "" },
  { name: "Бутылка 3 л. \"Ностальгия\", шт", price: 524.0, stock: 1.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутылка 3 л. \"Ностальгия\" бронза, шт", price: 892.5, stock: 2.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутылка 3 л. \"Ностальгия\" зелёная, шт", price: 892.5, stock: 2.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутылка 3 л. \"Ностальгия\" красная, шт", price: 892.5, stock: 1.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутылка 3 л. \"Ностальгия\" синяя, шт", price: 892.5, stock: 4.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутылка 3 л. \"Ностальгия\" чёрная, шт", price: 892.5, stock: 5.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутылка 3 л. \"Фуфырь\" синяя, шт", price: 897.8, stock: 3.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутылка 4,5 л. \"Ровоам\" бронза, шт", price: 735.0, stock: 1.0, volume: "4.5 л", category: "bottles", diameter: "" },
  { name: "Бутылка 4,5 л. \"Ровоам\" синий, шт", price: 735.0, stock: 1.0, volume: "4.5 л", category: "bottles", diameter: "" },
  { name: "Бутыль 10л \"Дачная\" СКО (зеленый) /2 шт уп. , шт", price: 1260.0, stock: 6.0, volume: "10 л", category: "bottles", diameter: "" },
  { name: "Бутыль 10л \"Казак\" ТО d58 (зеленый)/2 шт уп. , шт", price: 1215.0, stock: 1.0, volume: "10 л", category: "bottles", diameter: "d58" },
  { name: "Бутыль 10л \"Казак\" ТО d58 (прозрачный)/2 шт уп. , шт", price: 1215.0, stock: 5.0, volume: "10 л", category: "bottles", diameter: "d58" },
  { name: "Бутыль 15л \"Дачная\" ТО d110  (прозрачный+крышка) /2 шт уп. , шт", price: 2000.0, stock: 3.0, volume: "15 л", category: "bottles", diameter: "d110" },
  { name: "Бутыль 15л \"Казак\" ТО d58 (зеленый)/2 шт уп. , шт", price: 2205.0, stock: 5.0, volume: "15 л", category: "bottles", diameter: "d58" },
  { name: "Бутыль 15л \"Казак\" ТО d58 (прозрачный)/2 шт уп. , шт", price: 1920.0, stock: 4.0, volume: "15 л", category: "bottles", diameter: "d58" },
  { name: "Бутыль 2л \"Винная\" проз. с пробкой/ 5шт уп, шт", price: 580.0, stock: 2.0, volume: "2 л", category: "bottles", diameter: "" },
  { name: "Бутыль 3л \"Дамижана\"/кор. 4шт., шт", price: 892.5, stock: 8.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутыль 3л \"Джон\"с крышкой/10шт уп, шт", price: 630.0, stock: 11.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутыль 3л \"Четверть\" с крышкой/5 шт уп, шт", price: 787.5, stock: 6.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутыль 3л \"Четверть\" с пробкой/5 шт уп, шт", price: 735.0, stock: 8.0, volume: "3 л", category: "bottles", diameter: "" },
  { name: "Бутыль 5л \"Виноград\" ТО d38 (зеленый) /4 шт уп. , шт", price: 1050.0, stock: 6.0, volume: "5 л", category: "bottles", diameter: "d38" },
  { name: "Бутыль 5л \"Дамижана\"/4, шт", price: 945.0, stock: 4.0, volume: "5 л", category: "bottles", diameter: "" },
  { name: "Бутыль 5л \"Дария\" проз. с крышкой/2 шт уп, шт", price: 870.0, stock: 6.0, volume: "5 л", category: "bottles", diameter: "" },
  { name: "Бутыль 7л \"Виноград\" ТО d38 (зеленый) /3 шт уп. , шт", price: 1102.5, stock: 4.0, volume: "7 л", category: "bottles", diameter: "d38" },
  { name: "Ванна 120 литров оцинкованная/3, шт", price: 2047.5, stock: 3.0, volume: "120 л", category: "home", diameter: "" },
  { name: "Ванна 60 литров оцинкованная/4, шт", price: 1365.0, stock: 13.0, volume: "60 л", category: "home", diameter: "" },
  { name: "Ванна 80 литров оцинкованная/4, шт", price: 1700.0, stock: 8.0, volume: "80 л", category: "home", diameter: "" },
  { name: "Ватрушка круглая d-0,75 м, шт", price: 1155.0, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Ватрушка круглая d-1,1м, шт", price: 1837.5, stock: 25.0, volume: "---", category: "home", diameter: "" },
  { name: "Ведро 10 л. \"Hot Pot\", шт", price: 1365.0, stock: 1.0, volume: "10 л", category: "containers", diameter: "" },
  { name: "Ведро 10 л. с крышкой (АП 053)/10, шт", price: 273.0, stock: 6.0, volume: "10 л", category: "lids", diameter: "" },
  { name: "Ведро 15 л. прямоугольное, шт", price: 210.0, stock: 16.0, volume: "15 л", category: "containers", diameter: "" },
  { name: "Ведро 15 л. с крышкой (АП 055)/10, шт", price: 309.8, stock: 4.0, volume: "15 л", category: "lids", diameter: "" },
  { name: "Ведро 15 л. хозяйственное (АП 063)/10, шт", price: 210.0, stock: 6.0, volume: "15 л", category: "containers", diameter: "" },
  { name: "Ведро 15 л. цветное (АП 054)/10, шт", price: 210.0, stock: 9.0, volume: "15 л", category: "containers", diameter: "" },
  { name: "Ведро 5 л. хозяйственное, шт", price: 73.5, stock: 20.0, volume: "5 л", category: "containers", diameter: "" },
  { name: "Ведро 8 л. хозяйственное (АП 062)/20, шт", price: 131.3, stock: 10.0, volume: "8 л", category: "containers", diameter: "" },
  { name: "Ведро д/мусора 10 литров с педалью, шт", price: 441.0, stock: 3.0, volume: "10 л", category: "containers", diameter: "" },
  { name: "Ведро оцинкованное 12 литров, шт", price: 315.0, stock: 2.0, volume: "12 л", category: "containers", diameter: "" },
  { name: "Ведро оцинкованное 15 литров/10, шт", price: 383.3, stock: 17.0, volume: "15 л", category: "containers", diameter: "" },
  { name: "Ведро оцинкованное 5 литров/10, шт", price: 220.5, stock: 3.0, volume: "5 л", category: "containers", diameter: "" },
  { name: "Ведро оцинкованное 7 литров/10, шт", price: 246.8, stock: 7.0, volume: "7 л", category: "containers", diameter: "" },
  { name: "Ведро оцинкованное 9 литров/10, шт", price: 294.0, stock: 7.0, volume: "9 л", category: "containers", diameter: "" },
  { name: "Ведро с крышкой 1 литр круглое/150, шт", price: 31.5, stock: 65.0, volume: "1 л", category: "lids", diameter: "" },
  { name: "Ведро с крышкой 5,7 литра круглое, белое/25, шт", price: 116.6, stock: 18.0, volume: "5.7 л", category: "lids", diameter: "" },
  { name: "Ведро-туалет 17 литров со сьёмным горшком/5, шт", price: 687.8, stock: 4.0, volume: "17 л", category: "containers", diameter: "" },
  { name: "Ведро-туалет 18 литров/5, шт", price: 435.8, stock: 20.0, volume: "18 л", category: "containers", diameter: "" },
  { name: "Веник бамбуковый массажный \"Банные штучки\"/20, шт", price: 367.5, stock: 13.0, volume: "---", category: "home", diameter: "" },
  { name: "Вешалка 3-х рожковая, липа, 25*6,5*7 \"Банные штучки\"/5, шт", price: 189.0, stock: 9.0, volume: "---", category: "home", diameter: "" },
  { name: "Вешалка 5-ти рожковая, липа, 45*6,5*7 \"Банные штучки\", шт", price: 294.0, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Вешалка 6-ти рожковая, липа, 55*6,5*7 \"Банные штучки\"/5, шт", price: 315.0, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Вилы 4-х рогие кованные*, шт", price: 336.0, stock: 16.0, volume: "---", category: "tools", diameter: "" },
  { name: "Вилы 4-х рогие навозные сварные из калиброванной стали, шт", price: 94.5, stock: 19.0, volume: "---", category: "tools", diameter: "" },
  { name: "Вилы подборочные широкие, шт", price: 383.3, stock: 8.0, volume: "---", category: "tools", diameter: "" },
  { name: "Виномер бытовой, шт", price: 47.3, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Войлок 1,5 м ширина *8мм толщина/плотность 800/10 м., пог. м", price: 651.0, stock: 4.6, volume: "---", category: "home", diameter: "" },
  { name: "Воронка d-140 для банок с большим горлом, шт", price: 84.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Воронка d-150, шт", price: 84.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Воронка d-150 голубая, шт", price: 84.0, stock: 14.0, volume: "---", category: "home", diameter: "" },
  { name: "Воронка d-75 мл, шт", price: 31.5, stock: 3.0, volume: "75 мл", category: "home", diameter: "" },
  { name: "Вставка теплицы \"Малыш\" 2м*2м/2, шт", price: 3465.0, stock: 2.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Вставка теплицы \"Основа-Люкс\" 3х2м двойная дуга, шт", price: 4700.0, stock: 5.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Вставка теплицы \"Основа\" 3м*2м/2, шт", price: 3300.0, stock: 12.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Выставочные образцы теплицы 3х2м, шт", price: 9000.0, stock: 1.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Газ универсальный СИБИАР 220мл/12, шт", price: 99.8, stock: 20.0, volume: "220 мл", category: "home", diameter: "" },
  { name: "Горелка газовая с пьезо \"Пламя\" М5, шт", price: 472.5, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Грабли витые 12-ти зубые, шт", price: 68.3, stock: 5.0, volume: "---", category: "tools", diameter: "" },
  { name: "Декстроза 1 кг, шт", price: 262.5, stock: 6.0, volume: "---", category: "home", diameter: "" },
  { name: "Долерит (10 кг, ведро, мытый), шт", price: 1044.8, stock: 1.0, volume: "---", category: "containers", diameter: "" },
  { name: "Дрова колотые в сетке/10л., шт", price: 178.5, stock: 16.0, volume: "10 л", category: "home", diameter: "" },
  { name: "Дрожжи \"TURBO MegaPack\" 100 литров, шт", price: 451.5, stock: 10.0, volume: "100 л", category: "home", diameter: "" },
  { name: "Дрожжи \"Бекмая\" сухие 80 гр./50, шт", price: 47.3, stock: 141.0, volume: "---", category: "home", diameter: "" },
  { name: "Дрожжи \"Красноярские\" 100 гр./50, шт", price: 68.3, stock: 67.0, volume: "---", category: "home", diameter: "" },
  { name: "Дрожжи Pack 100L/360гр/25, шт", price: 703.5, stock: 8.0, volume: "---", category: "home", diameter: "" },
  { name: "Дрожжи Турбо С48/130гр/40, шт", price: 300.0, stock: 282.0, volume: "---", category: "home", diameter: "" },
  { name: "Живая земля универсал /грунт Terra Vita/ 5 литров, шт", price: 89.3, stock: 84.0, volume: "5 л", category: "home", diameter: "" },
  { name: "З-45/1,8м Заборная решетка/25м, пог. м", price: 267.8, stock: 24.0, volume: "---", category: "home", diameter: "" },
  { name: "З-50/2м Заборная решетка/25м, пог. м", price: 315.0, stock: 25.0, volume: "---", category: "home", diameter: "" },
  { name: "З-70/1,5м Заборная решетка/20м, пог. м", price: 504.0, stock: 3.5, volume: "---", category: "home", diameter: "" },
  { name: "Зажим Гофмана (Т-образный) для трубок, 12мм (нержавеющая сталь), шт", price: 136.5, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Казан 10л чугунный с алюм. крышкой с дужкой/MANOLI Беларусь, шт", price: 6436.5, stock: 1.0, volume: "10 л", category: "lids", diameter: "" },
  { name: "Казан 4л азиатский чугунный/Бризолль Украина, шт", price: 4887.8, stock: 1.0, volume: "4 л", category: "home", diameter: "" },
  { name: "Казан 5,5л чугунный с чугун. крышкой/Апекс, шт", price: 5880.0, stock: 2.0, volume: "5.5 л", category: "lids", diameter: "" },
  { name: "Казан 6л /кастрюля чугунный ст/кр. d=320/Ситон Украина, шт", price: 4777.5, stock: 2.0, volume: "6 л", category: "home", diameter: "" },
  { name: "Казан 6л чугунный с чугун. крышкой-ск./МАNOLI Беларусь, шт", price: 5381.3, stock: 1.0, volume: "6 л", category: "lids", diameter: "" },
  { name: "Казан 6л чугунный стекл. крышка/MANOLI Беларусь, шт", price: 3675.0, stock: 2.0, volume: "6 л", category: "lids", diameter: "" },
  { name: "Казан 8л чугунный с чугун. крышкой-ск/Бризолль Украина, шт", price: 6037.5, stock: 1.0, volume: "8 л", category: "lids", diameter: "" },
  { name: "Казан 8л чугунный/MANOLI Беларусь, шт", price: 3990.0, stock: 1.0, volume: "8 л", category: "home", diameter: "" },
  { name: "Канистра 10 л. со сливом (уп.6), шт", price: 304.5, stock: 5.0, volume: "10 л", category: "containers", diameter: "" },
  { name: "Канистра 10 л. стальная краш., шт", price: 1239.0, stock: 1.0, volume: "10 л", category: "containers", diameter: "" },
  { name: "Канистра 15 л. со сливом (уп.4), шт", price: 441.0, stock: 6.0, volume: "15 л", category: "containers", diameter: "" },
  { name: "Канистра 20 л. \"Бочонок\", шт", price: 577.5, stock: 1.0, volume: "20 л", category: "containers", diameter: "" },
  { name: "Канистра 20 л. алюминиевая/3, шт", price: 3444.0, stock: 1.0, volume: "20 л", category: "containers", diameter: "" },
  { name: "Канистра 22 л. со сливом (уп.4), шт", price: 735.0, stock: 3.0, volume: "22 л", category: "containers", diameter: "" },
  { name: "Канистра 25 л. \"Бочонок\" (уп 4), шт", price: 588.0, stock: 5.0, volume: "25 л", category: "containers", diameter: "" },
  { name: "Канистра 25 л. со сливом (уп.4), шт", price: 666.8, stock: 13.0, volume: "25 л", category: "containers", diameter: "" },
  { name: "Канистра 3 л. Арт.303/15, шт", price: 68.3, stock: 10.0, volume: "3 л", category: "containers", diameter: "" },
  { name: "Канистра 31,5 л. Арт.3001-ПЩ/4, шт", price: 535.5, stock: 9.0, volume: "31.5 л", category: "containers", diameter: "" },
  { name: "Канистра 5 л. Арт.502-Н/12, шт", price: 99.8, stock: 4.0, volume: "5 л", category: "containers", diameter: "" },
  { name: "Канистра 50 л. \"Бочонок\" с навесными ручками (уп.2), шт", price: 1207.5, stock: 1.0, volume: "50 л", category: "containers", diameter: "" },
  { name: "Канистра- Бочка 110л. прям (диам.горл.215мм) (уп.2), шт", price: 2205.0, stock: 2.0, volume: "110 л", category: "containers", diameter: "" },
  { name: "Канистра- Бочка 20л. прямоугольная/6, шт", price: 693.0, stock: 2.0, volume: "20 л", category: "containers", diameter: "" },
  { name: "Канистра- Бочка 25 литров, шт", price: 840.0, stock: 1.0, volume: "25 л", category: "containers", diameter: "" },
  { name: "Канистра- Бочка 25 литров, шт", price: 840.0, stock: 1.0, volume: "25 л", category: "containers", diameter: "" },
  { name: "Канистра- Бочка 40л. (горл.215мм) с навесной ручкой (уп.4), шт", price: 997.5, stock: 7.0, volume: "40 л", category: "containers", diameter: "" },
  { name: "Канистра- Бочка 50л.\"Байкал- эконом\" с навесной ручкой (уп.4), шт", price: 819.0, stock: 2.0, volume: "50 л", category: "containers", diameter: "" },
  { name: "Канистра- Бутыль с ручкой 20 литров/6, шт", price: 420.0, stock: 3.0, volume: "20 л", category: "bottles", diameter: "" },
  { name: "Каркас теплицы \"Малыш\" 2м*4м/ 2 упак, шт", price: 14070.0, stock: 2.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Каркас теплицы \"Основа-Люкс\" 3х4м двойная дуга, шт", price: 16500.0, stock: 4.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Каркас теплицы \"Основа\" 3м*4м/2, шт", price: 14070.0, stock: 16.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Керосин 0,5л стекло, шт", price: 73.5, stock: 11.0, volume: "0.5 л", category: "home", diameter: "" },
  { name: "Керосин 5 литров канистра, шт", price: 756.0, stock: 8.0, volume: "5 л", category: "containers", diameter: "" },
  { name: "Кисть плоская \"Кошка\" 25*12, светлая натуральная щетина  0126010/12шт, шт", price: 18.9, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Клюшка хоккейная, шт", price: 78.8, stock: 10.0, volume: "---", category: "home", diameter: "" },
  { name: "Ковш - черпак 1,5л. бондарный с горизонтальной ручкой \"Банные штучки\"/5, шт", price: 861.0, stock: 6.0, volume: "1.5 л", category: "home", diameter: "" },
  { name: "Ковш 3 литра оцинкованный, шт", price: 315.0, stock: 17.0, volume: "3 л", category: "home", diameter: "" },
  { name: "Ковшик большой для бани (1,2л) нержав., шт", price: 624.8, stock: 3.0, volume: "1.2 л", category: "home", diameter: "" },
  { name: "Колпак для масляной бутылки с дозатором В-31,5*24 цв. черный (уп 2200шт.), шт", price: 18.0, stock: 120.0, volume: "---", category: "bottles", diameter: "" },
  { name: "Колпак для Оливы, цв. чёрный, В-31*24, шт", price: 18.0, stock: 207.0, volume: "---", category: "home", diameter: "" },
  { name: "Колпачок 28 мм Двухкомпонентный Белый /4600 , шт", price: 1.1, stock: 2658.0, volume: "---", category: "lids", diameter: "" },
  { name: "Колпачок 28 мм Черный 99222 S/4200, шт", price: 1.1, stock: 2985.0, volume: "---", category: "lids", diameter: "" },
  { name: "Колпачок алюминиевый 28*18 мм черный (без резьбы), шт", price: 4.2, stock: 2018.0, volume: "---", category: "lids", diameter: "" },
  { name: "Колпачок Гуала под бутылку золотая, зелёная, шт", price: 6.8, stock: 155.0, volume: "---", category: "bottles", diameter: "" },
  { name: "Колпачок Гуала под бутылку, кпм-30 чёрный, шт", price: 14.2, stock: 5.0, volume: "---", category: "bottles", diameter: "" },
  { name: "Коптильня большая с поддоном (500*270*175) сталь 0,8мм, двухьярусная, шт", price: 1312.5, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Кочерга кованная черная 51 см \"Печные штучки\"\"/10, шт", price: 735.0, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Кран для бочки из дуба, шт", price: 367.5, stock: 4.0, volume: "---", category: "containers", diameter: "" },
  { name: "Крепление для теплиц в грунт, шт", price: 126.0, stock: 51.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Крышка d100 мм золото г. Елабуга/260, шт", price: 12.1, stock: 209.0, volume: "---", category: "lids", diameter: "d100" },
  { name: "Крышка d18 мм алюминиевая серебристая, шт", price: 8.0, stock: 455.0, volume: "---", category: "lids", diameter: "d18" },
  { name: "Крышка d28 мм алюминиевая золото, шт", price: 8.9, stock: 1328.0, volume: "---", category: "lids", diameter: "d28" },
  { name: "Крышка d28 мм алюминиевая серебристая, шт", price: 8.9, stock: 1967.0, volume: "---", category: "lids", diameter: "d28" },
  { name: "Крышка d43 мм белая/3300, шт", price: 8.8, stock: 22.0, volume: "---", category: "lids", diameter: "d43" },
  { name: "Крышка d43 мм золото Магол/3300, шт", price: 5.5, stock: 4760.0, volume: "---", category: "lids", diameter: "d43" },
  { name: "Крышка d43 мм красная Магол/3300, шт", price: 5.5, stock: 1548.0, volume: "---", category: "lids", diameter: "d43" },
  { name: "Крышка d48 мм золото/2500, шт", price: 6.9, stock: 9214.0, volume: "---", category: "lids", diameter: "d48" },
  { name: "Крышка d51 мм белая (стер) с клапаном/1900, шт", price: 9.5, stock: 1969.0, volume: "---", category: "lids", diameter: "d51" },
  { name: "Крышка d53 мм золото Магол/1800, шт", price: 6.3, stock: 822.0, volume: "---", category: "lids", diameter: "d53" },
  { name: "Крышка d58 мм \"Пчелка\"/1600, шт", price: 6.8, stock: 556.0, volume: "---", category: "lids", diameter: "d58" },
  { name: "Крышка d58 мм DEEP серебро/1320шт.уп, шт", price: 13.1, stock: 1058.0, volume: "---", category: "lids", diameter: "d58" },
  { name: "Крышка d58 мм белая г. Елабуга/1150, шт", price: 5.7, stock: 3096.0, volume: "---", category: "lids", diameter: "d58" },
  { name: "Крышка d58 мм золото г. Елабуга/1150, шт", price: 6.0, stock: 5561.0, volume: "---", category: "lids", diameter: "d58" },
  { name: "Крышка d58 мм красная г. Елабуга/1150, шт", price: 6.0, stock: 1306.0, volume: "---", category: "lids", diameter: "d58" },
  { name: "Крышка d58 мм черная  г. Елабуга/1150, шт", price: 5.7, stock: 9089.0, volume: "---", category: "lids", diameter: "d58" },
  { name: "Крышка d63 мм золотая Магол/1300, шт", price: 7.6, stock: 1300.0, volume: "---", category: "lids", diameter: "d63" },
  { name: "Крышка d66 мм \"Пчелка\"/1250, шт", price: 7.9, stock: 870.0, volume: "---", category: "lids", diameter: "d66" },
  { name: "Крышка d66 мм DEEP золото Китай/900 шт.уп, шт", price: 16.4, stock: 949.0, volume: "---", category: "lids", diameter: "d66" },
  { name: "Крышка d66 мм DEEP золото Магол/800 шт.уп, шт", price: 13.7, stock: 48.0, volume: "---", category: "lids", diameter: "d66" },
  { name: "Крышка d66 мм DEEP серебро Магол/800 шт.уп, шт", price: 12.6, stock: 452.0, volume: "---", category: "lids", diameter: "d66" },
  { name: "Крышка d66 мм DEEP черная матовая Магол/800 шт.уп, шт", price: 13.7, stock: 773.0, volume: "---", category: "lids", diameter: "d66" },
  { name: "Крышка d66 мм белая г. Елабуга/800, шт", price: 7.4, stock: 5924.0, volume: "---", category: "lids", diameter: "d66" },
  { name: "Крышка d66 мм золото г. Елабуга/800, шт", price: 7.4, stock: 3936.0, volume: "---", category: "lids", diameter: "d66" },
  { name: "Крышка d66 мм красная г. Елабуга/800, шт", price: 7.4, stock: 2774.0, volume: "---", category: "lids", diameter: "d66" },
  { name: "Крышка d66 мм чёрная г. Елабуга/800, шт", price: 7.4, stock: 7434.0, volume: "---", category: "lids", diameter: "d66" },
  { name: "Крышка d70 мм золото/1150, шт", price: 13.0, stock: 269.0, volume: "---", category: "lids", diameter: "d70" },
  { name: "Крышка d77 мм серебро Магол/900шт. уп, шт", price: 11.0, stock: 9.0, volume: "---", category: "lids", diameter: "d77" },
  { name: "Крышка d82 Автоклавирование г. Елабуга/240/20 блок, шт", price: 11.0, stock: 160.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d82 мм \"Пчелка\"/750, шт", price: 16.8, stock: 652.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d82 мм белая г. Елабуга/500, шт", price: 8.9, stock: 9266.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d82 мм золотая (стерилизация) г. Елабуга/500, шт", price: 8.7, stock: 7047.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d82 мм золотая г. Елабуга/500, шт", price: 9.0, stock: 5609.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d82 мм красная г. Елабуга/500, шт", price: 9.0, stock: 600.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d82 мм чёрная г. Елабуга/500, шт", price: 9.1, stock: 2229.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d82 СКО \"Автоклавирование\" г. Елабуга/600/50/25, шт", price: 7.5, stock: 2050.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d82 СКО \"Гарантия Качества\" г. Елабуга/600/50, шт", price: 6.7, stock: 1350.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d82 СКО золото г. Екатеринбург/600/50, шт", price: 3.7, stock: 650.0, volume: "---", category: "lids", diameter: "d82" },
  { name: "Крышка d89 мм золото г. Елабуга/370, шт", price: 12.1, stock: 367.0, volume: "---", category: "lids", diameter: "d89" },
  { name: "Крючок ветровой 1/100, шт", price: 52.5, stock: 86.0, volume: "---", category: "home", diameter: "" },
  { name: "Кувалда 3 кг с ручкой, шт", price: 504.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Ледоруб с топором с металлической ручкой Б-3, шт", price: 472.5, stock: 6.0, volume: "---", category: "home", diameter: "" },
  { name: "Ледянки \"Ветерок\", шт", price: 89.3, stock: 32.0, volume: "---", category: "home", diameter: "" },
  { name: "Лейка 2л. \"Лотос\" (для комнатных растений) /10, шт", price: 157.5, stock: 2.0, volume: "2 л", category: "home", diameter: "" },
  { name: "Лейка п/э 10 литров, шт", price: 204.8, stock: 30.0, volume: "10 л", category: "home", diameter: "" },
  { name: "Лента бордюрная высота 10 см, шт", price: 367.5, stock: 11.0, volume: "---", category: "home", diameter: "" },
  { name: "Лента бордюрная высота 10 см, длина 10 м. Бердск, шт", price: 220.5, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Лента бордюрная высота 15 см, шт", price: 504.0, stock: 8.0, volume: "---", category: "home", diameter: "" },
  { name: "Лента бордюрная высота 30 см, длина 10 м. Бердск, шт", price: 598.5, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Лента бордюрная высота 30 см, длина 30 м коричневая, шт", price: 2499.0, stock: 8.0, volume: "---", category: "home", diameter: "" },
  { name: "Лимонадник 3л \"Кристалл\" с краном, шт", price: 2572.5, stock: 3.0, volume: "3 л", category: "home", diameter: "" },
  { name: "Лимонадник 5л \"Колба\" с краном/6 шт, шт", price: 1522.5, stock: 2.0, volume: "5 л", category: "home", diameter: "" },
  { name: "Лимонадник 7л \"Колба\" с краном/6 шт, шт", price: 1680.0, stock: 1.0, volume: "7 л", category: "home", diameter: "" },
  { name: "Лимонадник 8л \"Амфора\" с краном, шт", price: 1890.0, stock: 2.0, volume: "8 л", category: "home", diameter: "" },
  { name: "Лист СПК \"Berolux\" (2100*6000*4мм) бесцветный/0,7, шт", price: 4567.5, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Kronos Premium (2100*6000*4мм) прозрачный 0,63, шт", price: 3800.0, stock: 51.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Sellex Premium (2100*6000*4мм) прозрачный 0,8, шт", price: 5000.0, stock: 85.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Sellex Solaris (2100*6000*4мм) прозрачный 0,54, шт", price: 3100.0, stock: 496.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Бирюзовый (2100*6000*4мм) , шт", price: 3622.5, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Желтый (2100*6000*4мм) , шт", price: 3622.5, stock: 6.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Зелёный (2100*6000*4мм) , шт", price: 3450.0, stock: 20.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Коричневый (2100*6000*4мм) , шт", price: 3450.0, stock: 51.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Молочный (2100*6000*4мм) , шт", price: 3622.5, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Оранжевый (2100*6000*4мм) , шт", price: 3622.5, stock: 52.0, volume: "---", category: "home", diameter: "" },
  { name: "Лист СПК Синий (2100*6000*4мм), шт", price: 3450.0, stock: 13.0, volume: "---", category: "home", diameter: "" },
  { name: "Лопата \"БОГАТЫРЬ №2\" 480*360мм с метал. черенком, v-ручкой, шт", price: 346.5, stock: 13.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лопата \"РУСИЧ-7\" оцинкованная 428*375*0,8мм с деревянным черенком, шт", price: 346.5, stock: 9.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лопата без черенка \"Санта\" 420*400 мм PROTEX. До -30 С, шт", price: 420.0, stock: 75.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лопата без черенка \"Снежная королева\" 445*330 мм PROTEX. До -30 С, шт", price: 472.5, stock: 60.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лопата без черенка №16. 500*445мм, шт", price: 367.5, stock: 2.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лопата без черенка Альфа 460*420мм/d40 (АП 081), шт", price: 315.0, stock: 37.0, volume: "---", category: "tools", diameter: "d40" },
  { name: "Лопата без черенка из Поликарбоната Красная 430*420мм/d35. До -60 С, шт", price: 740.0, stock: 11.0, volume: "---", category: "tools", diameter: "d35" },
  { name: "Лопата без черенка стальная 380*355мм с накладкой порош. окраска, шт", price: 94.5, stock: 1.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лопата без черенка Титан 470*360мм (АП 086), шт", price: 315.0, stock: 10.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лопата без черенка тротуарная 428*375*0,8мм оцинкованная, шт", price: 199.5, stock: 8.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лопата облегчённая штыковая, шт", price: 120.8, stock: 45.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лопатка детская L-580мм, шт", price: 115.5, stock: 6.0, volume: "---", category: "tools", diameter: "" },
  { name: "Лыжи детские \"Олимпик-спорт\"с палками, 66/75см, крепление мягкое пластиковое, шт", price: 672.0, stock: 17.0, volume: "---", category: "home", diameter: "" },
  { name: "Мангал сталь 0,4мм (350*250*350) сборный, шт", price: 262.5, stock: 19.0, volume: "---", category: "home", diameter: "" },
  { name: "Мангал сталь 1,5мм (700*300*700) сборный, шт", price: 2257.5, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Мегаспан ПЛ 10мм/30п.м, м", price: 94.5, stock: 35.5, volume: "---", category: "home", diameter: "" },
  { name: "Мегаспан ПЛ 5мм/50п.м, м", price: 63.0, stock: 1.4, volume: "---", category: "home", diameter: "" },
  { name: "Мерный стакан 0,500л., шт", price: 84.0, stock: 34.0, volume: "0.500 л", category: "home", diameter: "" },
  { name: "Мерный стакан 1л. пластик, шт", price: 105.0, stock: 8.0, volume: "1 л", category: "home", diameter: "" },
  { name: "Мерный стакан 2л. пластик, шт", price: 210.0, stock: 4.0, volume: "2 л", category: "home", diameter: "" },
  { name: "Мерный стакан 5л. пластик, шт", price: 399.0, stock: 5.0, volume: "5 л", category: "home", diameter: "" },
  { name: "Метла без черенка, шт", price: 157.5, stock: 37.0, volume: "---", category: "tools", diameter: "" },
  { name: "Метла хоз. с круглым основанием с 4 решётками, шт", price: 233.0, stock: 268.0, volume: "---", category: "tools", diameter: "" },
  { name: "Мешок п/п 55*95 белый/57гр. (Китай), шт", price: 16.3, stock: 428.0, volume: "---", category: "home", diameter: "" },
  { name: "Мешок п/п 55*95 зеленый (Китай)/1000, шт", price: 10.5, stock: 270.0, volume: "---", category: "home", diameter: "" },
  { name: "Мини-лыжи, шт", price: 94.5, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Мини-лыжи \"Юниор\", шт", price: 231.0, stock: 32.0, volume: "---", category: "home", diameter: "" },
  { name: "Молоток -гвоздодер STAVER с деревянной рукояткой ,450 г, шт", price: 294.0, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Молоток 888/500гр фиберглас. ручка , шт", price: 294.0, stock: 6.0, volume: "---", category: "home", diameter: "" },
  { name: "Москитная сетка 1,4м ширина/30 метров, пог. м", price: 141.8, stock: 69.25, volume: "---", category: "home", diameter: "" },
  { name: "Набор посуды №6 Для всей семьи, шт", price: 105.0, stock: 24.0, volume: "---", category: "home", diameter: "" },
  { name: "Настойка \"Бехеровка\", шт", price: 110.3, stock: 9.0, volume: "---", category: "home", diameter: "" },
  { name: "Настойка \"БЛЮ-КЮРАСАО\", шт", price: 162.8, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Настойка \"Джин\", шт", price: 110.3, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Настойка \"Зубровка\", шт", price: 110.3, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Настойка \"Ром\", шт", price: 110.3, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Настойка \"Фруктовый коньяк\", шт", price: 162.8, stock: 13.0, volume: "---", category: "home", diameter: "" },
  { name: "Нефрит колото-пиленый (10 кг, мытый) ведро, шт", price: 4252.5, stock: 1.0, volume: "---", category: "containers", diameter: "" },
  { name: "Опрыскиватель 1 литр \"Лазурит\", шт", price: 94.5, stock: 21.0, volume: "1 л", category: "home", diameter: "" },
  { name: "Опрыскиватель заплечный \"Жук\" 5 литров/4, шт", price: 1806.0, stock: 3.0, volume: "5 л", category: "home", diameter: "" },
  { name: "Отвод 3/4, шт", price: 315.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Пакет для мусора 160 литров/90*110 чёрный/10шт, шт", price: 99.8, stock: 124.0, volume: "160 л", category: "home", diameter: "" },
  { name: "Пакет для мусора 200 литров/90*120 чёрный/10шт, шт", price: 131.3, stock: 72.0, volume: "200 л", category: "home", diameter: "" },
  { name: "Пакет для мусора 240 литров/95*130 чёрный/10шт, шт", price: 152.3, stock: 66.0, volume: "240 л", category: "home", diameter: "" },
  { name: "Пакет майка ПНД 40*65см (20мкн), шт", price: 5.3, stock: 110.0, volume: "---", category: "home", diameter: "" },
  { name: "Пакет фасовочный ПНД 25*40см, шт", price: 336.0, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Парник 6,5м /Агротекс № 35/дуга 2м/20мм/колышки, клипсы, шт", price: 577.5, stock: 1.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Пена монт проф PROFF 65 ++ARKTIKA /1000мл/940гр/12, шт", price: 572.3, stock: 1.0, volume: "1000 мл", category: "home", diameter: "" },
  { name: "Перчатки \"Зима-40\", шт", price: 315.0, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Перчатки \"Люкс\" нейлоновые чёрные, шт", price: 157.5, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Перчатки \"Торро\" утепленные усиленные ЛЮКС, шт", price: 73.5, stock: 5.0, volume: "---", category: "home", diameter: "" },
  { name: "Перчатки \"ЦВЕТОЧЕК\" нейлоновые , шт", price: 42.0, stock: 194.0, volume: "---", category: "home", diameter: "" },
  { name: "Перчатки зимние на флисе, шт", price: 136.5, stock: 24.0, volume: "---", category: "home", diameter: "" },
  { name: "Перчатки ЛЮКС двойные шерстяные, шт", price: 105.0, stock: 25.0, volume: "---", category: "home", diameter: "" },
  { name: "Перчатки ПВХ Х/Б (6/7,5) плотные чёрные/300, шт", price: 31.5, stock: 214.0, volume: "---", category: "home", diameter: "" },
  { name: "Перчатки хозяйственные (размер S), шт", price: 27.3, stock: 76.0, volume: "---", category: "home", diameter: "" },
  { name: "Плёнка воздушно-пузырьковая ВПП 2-10-65/1,6м/100 п.м., пог. м", price: 36.8, stock: 593.3, volume: "---", category: "agriculture", diameter: "" },
  { name: "Пленка голубая для пруда 0,350*(1500*2)/50, пог. м", price: 262.5, stock: 103.4, volume: "---", category: "agriculture", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,060*(1500*2)/ 27,60 кг технического назначения/200м, пог. м", price: 22.5, stock: 4215.6, volume: "---", category: "home", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,080*(1500*2) 18кг/100 п/м, пог. м", price: 60.0, stock: 1099.4, volume: "---", category: "home", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,100*(1500*2) 22,5кг - 100 п/м, пог. м", price: 74.0, stock: 1133.8, volume: "---", category: "home", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,100*(3000*2) 22,5кг - 50 п/м, пог. м", price: 151.0, stock: 550.75, volume: "---", category: "home", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,120*(1500*2) 27кг - 100 п/м, пог. м", price: 89.0, stock: 722.4, volume: "---", category: "home", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,120*(3000*2) 27кг - 50 п/м, пог. м", price: 181.5, stock: 519.7, volume: "---", category: "home", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,150*(1500*2) 33,7кг - 100 п/м, пог. м", price: 111.0, stock: 398.6, volume: "---", category: "home", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,150*(3000*2) 33,7кг - 50 п/м, пог. м", price: 226.5, stock: 599.2, volume: "---", category: "home", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,200*(1500*2) 22,5кг - 50 п/м, пог. м", price: 147.5, stock: 674.95, volume: "---", category: "home", diameter: "" },
  { name: "Пленка п/э, Н, рукав, 0,200*(3000*2) 45кг - 50п/м, пог. м", price: 302.0, stock: 570.6, volume: "---", category: "home", diameter: "" },
  { name: "Пленка чёрная п/э, Н, рукав, 0,100*(1500*2)/100, пог. м", price: 84.0, stock: 25.0, volume: "---", category: "home", diameter: "" },
  { name: "Подголовник липовый, мягкий  30,5*30*9,5 \"Банные штучки\"/8, шт", price: 735.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Подголовник липовый, мягкий, большой, 60*35*10 \"Банные штучки\"/6, шт", price: 997.5, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Полка с вешалкой 6 рожков  54*31*14 см \"Банные штучки\"/2, шт", price: 1029.0, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Полка с полотенцесушителем одинарный, липа, 44*22*9 \"Банные штучки\", шт", price: 336.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Полка угловая трехъярусная 76*33*11см \"Банные штучки\"/4, шт", price: 708.8, stock: 9.0, volume: "---", category: "home", diameter: "" },
  { name: "Прибор контроль крепости \"Попугай\" V=250, шт", price: 525.0, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Пробка Камю коньячная полимерная с доп. верхом РС-29/20-ИД, шт", price: 5.8, stock: 2067.0, volume: "---", category: "home", diameter: "" },
  { name: "Профиль соединительный 4мм прозрачный/60, шт", price: 370.0, stock: 119.0, volume: "---", category: "home", diameter: "" },
  { name: "Профиль торцевой 4мм прозрачный/200, шт", price: 70.15, stock: 513.0, volume: "---", category: "home", diameter: "" },
  { name: "Пруд п/э 210 литров. КЛУМБА (100*30см) чёрная, шт", price: 1732.5, stock: 2.0, volume: "210 л", category: "agriculture", diameter: "" },
  { name: "Пруд п/э 480 литров круглый (133*133*42см) чёрный, шт", price: 6037.5, stock: 1.0, volume: "480 л", category: "agriculture", diameter: "" },
  { name: "Пруд п/э 640 литров (2,45*1,28*0,6) чёрный, шт", price: 6825.0, stock: 1.0, volume: "640 л", category: "agriculture", diameter: "" },
  { name: "Пруд п/э 900 литров (240*150*60см) чёрный, шт", price: 8977.5, stock: 1.0, volume: "900 л", category: "agriculture", diameter: "" },
  { name: "ПЭТ бутылка 0,5 л. с колпачком/110, шт", price: 13.7, stock: 150.0, volume: "0.5 л", category: "bottles", diameter: "" },
  { name: "ПЭТ бутылка 1,5 л арт.1528 (упак.70шт.) плотная, шт", price: 20.5, stock: 340.0, volume: "1.5 л", category: "bottles", diameter: "" },
  { name: "ПЭТ бутылка 1л. арт.1028 (упак.72шт.), шт", price: 13.7, stock: 128.0, volume: "1 л", category: "bottles", diameter: "" },
  { name: "ПЭТ бутылка 5л. арт.5038/28, шт", price: 37.0, stock: 84.0, volume: "5 л", category: "bottles", diameter: "" },
  { name: "Пэт-бутыль 18,9 л голубая № 1 с ручкой/4 шт, шт", price: 378.0, stock: 5.0, volume: "18.9 л", category: "bottles", diameter: "" },
  { name: "Разбрызгиватель форсунка,пластик, шт", price: 52.5, stock: 5.0, volume: "---", category: "home", diameter: "" },
  { name: "Решетка на пол 50*100*3 см для бани и сауны (липа) \"Банные штучки\"/6, шт", price: 1386.0, stock: 11.0, volume: "---", category: "home", diameter: "" },
  { name: "Решетка на пол 60*70*3 см для бани и сауны (липа) \"Банные штучки\"/5, шт", price: 1207.5, stock: 9.0, volume: "---", category: "home", diameter: "" },
  { name: "Русский душ 20 л, липа, обливное устройство с пластиковой вставкой и наливным клапаном Банные штучки, шт", price: 3570.0, stock: 1.0, volume: "20 л", category: "home", diameter: "" },
  { name: "Ручка дверная кольцо, липа, 115мм \"Банные штучки\", шт", price: 267.8, stock: 15.0, volume: "---", category: "home", diameter: "" },
  { name: "Ручка дверная круглая 55 мм ( в комплекте 2 шт.) \"Банные штучки\"/10, шт", price: 472.5, stock: 8.0, volume: "---", category: "home", diameter: "" },
  { name: "Ручка для Стеклобанок - d82/700/500, шт", price: 6.3, stock: 1403.0, volume: "---", category: "home", diameter: "d82" },
  { name: "Ручка для черенка d-36, шт", price: 42.0, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Самогонный аппарат Славянка Премиум 20 литров (бытовой дистиллятор), шт", price: 6630.8, stock: 1.0, volume: "20 л", category: "home", diameter: "" },
  { name: "Саморезы кров.цинк,сверло с рез прокладкой 5,5*25 (250шт), шт", price: 3.2, stock: 3830.0, volume: "---", category: "home", diameter: "" },
  { name: "Сани рыбацкие \"Гигант\" с ручкой (3 сегмента) (1185*590*256), шт", price: 1417.5, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Сани рыбацкие С-1/1 (820*420*200), шт", price: 840.0, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Сани рыбацкие С-2 (880*420*140), шт", price: 840.0, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Сани рыбацкие С-3 (920*690*240), шт", price: 1596.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Сани рыбацкие С-5 (1200*600*250), шт", price: 1850.0, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Санки детские ВЭЛ-1, шт", price: 696.2, stock: 16.0, volume: "---", category: "tools", diameter: "" },
  { name: "Санки детские ВЭЛ-4ДК (2 пласт. колеса), шт", price: 892.5, stock: 24.0, volume: "---", category: "tools", diameter: "" },
  { name: "Сетка овощная 50*80/3000, шт", price: 10.5, stock: 1884.0, volume: "---", category: "home", diameter: "" },
  { name: "Сетка от птиц 4м*5м \"Ягодка\", шт", price: 220.5, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Сетка от птиц. Клубничка. Размер 2м*5м., шт", price: 420.0, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Сетка Панченкова. Рукав сетчатый гофрированый. Нержав., пог. м", price: 189.0, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Сетка сварная 1,2м оцинкованная ПВХ (100*75мм)/10 метров, пог. м", price: 288.8, stock: 10.0, volume: "---", category: "home", diameter: "" },
  { name: "Сетка сварная 1,5м оцинкованная (50*50мм)/15 метров, пог. м", price: 315.0, stock: 15.0, volume: "---", category: "home", diameter: "" },
  { name: "Скорлупа кедрового ореха/150гр., шт", price: 84.0, stock: 5.0, volume: "---", category: "home", diameter: "" },
  { name: "Скотч 48мм*120м/40мк/6 прозрачный, шт", price: 105.0, stock: 6.0, volume: "---", category: "home", diameter: "" },
  { name: "Скрепер для снега \"Таран\" на колёсах 68*63см (АП 084), шт", price: 1650.0, stock: 8.0, volume: "---", category: "home", diameter: "" },
  { name: "Снегокат детский 102-32 \"Russian Winter\" (красный), шт", price: 2100.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Совок печной кованный 4ПС1, шт", price: 808.5, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Совок хоз. метал. с вертикальной метал. ручкой, шт", price: 130.0, stock: 14.0, volume: "---", category: "home", diameter: "" },
  { name: "Совок хоз. метал. с длинной ручкой, шт", price: 130.0, stock: 16.0, volume: "---", category: "home", diameter: "" },
  { name: "Совок хозяйственный металлический зольный с длинной ручкой, шт", price: 78.8, stock: 34.0, volume: "---", category: "home", diameter: "" },
  { name: "Совок-ловушка (оцинкованный), шт", price: 420.0, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Спиртомер бытовой 0-96%, шт", price: 78.8, stock: 11.0, volume: "---", category: "home", diameter: "" },
  { name: "Стакан 0,250 л. \"питьевой\"/60шт.уп, шт", price: 24.0, stock: 60.0, volume: "0.250 л", category: "home", diameter: "" },
  { name: "Стеллаж-этажерка 32*29*119 см, липа \"Банные штучки\", шт", price: 3622.5, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Стол 120*90*72 см раскладной \"Банные штучки\", шт", price: 3360.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Стрейч плёнка вторичная 2 кг шир. 0,5 м, шт", price: 420.0, stock: 8.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Стрейч пленка первичная 1,8 кг шир. 0,5 м, шт", price: 525.0, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Табличка деревянная в ассортименте \"Банные штучки\" , шт", price: 357.0, stock: 8.0, volume: "---", category: "home", diameter: "" },
  { name: "Таз 16 литров 450мм алюминиевый, шт", price: 724.5, stock: 1.0, volume: "16 л", category: "home", diameter: "" },
  { name: "Таз 26 л. оцинкованный круглый/5, шт", price: 714.0, stock: 1.0, volume: "26 л", category: "home", diameter: "" },
  { name: "Таз 38 л. оцинкованный круглый, шт", price: 1050.0, stock: 1.0, volume: "38 л", category: "home", diameter: "" },
  { name: "Таз 38 л. п/э овальный цветной, шт", price: 315.0, stock: 5.0, volume: "38 л", category: "home", diameter: "" },
  { name: "Таз строительный круглый 120л., шт", price: 630.0, stock: 1.0, volume: "120 л", category: "home", diameter: "" },
  { name: "Талькохлорит обвалованный 20 кг (коробка), шт", price: 630.0, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр \"Банщик\" 23*10*3см для бани и сауны/5, шт", price: 1102.5, stock: 6.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр \"В здоровом теле-здоровый дух\" 19,8*13,4*3,3см для бани и сауны, шт", price: 1050.0, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр \"Рыба\" для бани и сауны, упак", price: 342.3, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр \"Удовольствие\" 16*16*2,5 см  для бани и сауны, упак", price: 892.5, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр бытовой ТБ-3-М1, исп.1, шт", price: 126.0, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр Д-3-2 ТУ, шт", price: 315.0, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр оконный Гвоздик Арт.ТСН-15, шт", price: 105.0, stock: 10.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр оконный Липучка ТБ-223, шт", price: 147.0, stock: 16.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр с гигрометром Банная станция \"Пар и жар\" 15*17*2,5 см для бани и сауны/10, шт", price: 1050.0, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Термометр-щуп цифровой ТР 101 без тубуса, шт", price: 157.5, stock: 4.0, volume: "---", category: "home", diameter: "" },
  { name: "Термопривод 300С/18, шт", price: 1470.0, stock: 46.0, volume: "---", category: "home", diameter: "" },
  { name: "Термоусадочный колпачок золото с алюм. верхом ТУК-А-30 мм, шт", price: 4.2, stock: 394.0, volume: "---", category: "lids", diameter: "" },
  { name: "Термошайба прозрачная для поликарбоната 4-10 мм/25, шт", price: 8.4, stock: 248.0, volume: "---", category: "home", diameter: "" },
  { name: "Тренога костровая 100см, в чехле, шт", price: 315.0, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Трубка силикон 8*1,5 мм, пог. м", price: 147.0, stock: 5.0, volume: "---", category: "home", diameter: "" },
  { name: "Туалет дачный \"Летний день\"/5, шт", price: 908.3, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Уголь кокосовый Extrasorb GAC, упакован в ведро/0,5 кг, шт", price: 267.8, stock: 14.0, volume: "---", category: "containers", diameter: "" },
  { name: "Умывальник 5 литров Летний день, шт", price: 378.0, stock: 6.0, volume: "5 л", category: "home", diameter: "" },
  { name: "Усилители для вставки 3*2м, (4шт + крепеж), шт", price: 945.0, stock: 11.0, volume: "---", category: "home", diameter: "" },
  { name: "Усилители для теплицы 3*4м (8шт + крепеж), шт", price: 1470.0, stock: 18.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Утеплитель для санок универсальный МЕХ (белый), шт", price: 347.6, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Утеплитель для санок универсальный МЕХ (красный), шт", price: 347.6, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Ф-15/1м Садовая решетка 15*15/20м зелёная, пог. м", price: 84.0, stock: 200.0, volume: "---", category: "home", diameter: "" },
  { name: "Ф-50/1м Садовая решетка 50*50/20м, пог. м", price: 126.0, stock: 59.05, volume: "---", category: "home", diameter: "" },
  { name: "Ф-83/1м Садовая решетка 83*83/20м, пог. м", price: 126.0, stock: 17.0, volume: "---", category: "home", diameter: "" },
  { name: "Фляга 60 литров (Арт.5004-окр)/2, шт", price: 1312.5, stock: 8.0, volume: "60 л", category: "containers", diameter: "" },
  { name: "Фляга 80 литров, шт", price: 1837.5, stock: 4.0, volume: "80 л", category: "containers", diameter: "" },
  { name: "Форточка дополнительная для теплицы 3*2, шт", price: 1522.5, stock: 3.0, volume: "---", category: "agriculture", diameter: "" },
  { name: "Хоккейный набор в блистере ( 2 клюшки+2 шайбы), шт", price: 231.0, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Хромит (10кг) ведро, шт", price: 875.7, stock: 12.0, volume: "---", category: "containers", diameter: "" },
  { name: "Цилиндр на пластм. основании 100мл со шкалой, шт", price: 126.0, stock: 2.0, volume: "100 мл", category: "home", diameter: "" },
  { name: "Цилиндр на пластм. основании 250мл со шкалой, шт", price: 157.5, stock: 3.0, volume: "250 мл", category: "home", diameter: "" },
  { name: "Цилиндр на пластм. основании 500мл со шкалой, шт", price: 210.0, stock: 3.0, volume: "500 мл", category: "home", diameter: "" },
  { name: "Чай Дары тайги Алтайский (краф пакет), шт", price: 246.8, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Чай Согревающий Алтайский (краф пакет), шт", price: 157.5, stock: 3.0, volume: "---", category: "home", diameter: "" },
  { name: "Чай Шиповник+ липа Алтайский (краф пакет), шт", price: 157.5, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Чай Энергия гор. Алтайский (краф пакет), шт", price: 189.0, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Часы кварцевые в предбанник для бани и сауны \" С легким паром\" 27*0,6 см  \"Банные штучки\", шт", price: 577.5, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Часы песочные 5 мин, пластиковый тубус, шт", price: 105.0, stock: 6.0, volume: "---", category: "home", diameter: "" },
  { name: "Черенок грабельный d28 мм/25, шт", price: 150.0, stock: 148.0, volume: "---", category: "home", diameter: "d28" },
  { name: "Черенок для лопаты d40 мм/1,3 (берёза) высший сорт/15, шт", price: 150.0, stock: 55.0, volume: "---", category: "tools", diameter: "d40" },
  { name: "Чесалка телескопическая в дисплей -боксе от 20 до 70 см \"Банные штучки\"/25, шт", price: 178.5, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Швабра деревянная в/с (берёза) 1,3м, шт", price: 126.0, stock: 124.0, volume: "---", category: "home", diameter: "" },
  { name: "Шланг ПВХ-Kаучук усиленный d18мм/20м, шт", price: 2493.8, stock: 3.0, volume: "---", category: "home", diameter: "d18" },
  { name: "Шланг резиновый 3/4 18 метров, шт", price: 577.5, stock: 5.0, volume: "---", category: "home", diameter: "" },
  { name: "Шпагат п/п /50 м, шт", price: 63.0, stock: 7.0, volume: "---", category: "home", diameter: "" },
  { name: "Щепа для копчения \"Бук\" 1 л, BOYSCOUT/25, шт", price: 94.5, stock: 38.0, volume: "1 л", category: "home", diameter: "" },
  { name: "Щепа для копчения \"Вишня\" 1 л, BOYSCOUT/25, шт", price: 126.0, stock: 17.0, volume: "1 л", category: "home", diameter: "" },
  { name: "Щепа для копчения \"Дуб\", 1л, BOYSCOUT/25, шт", price: 94.5, stock: 101.0, volume: "1 л", category: "home", diameter: "" },
  { name: "Щепа для копчения \"Слива\" 1л, BOYSCOUT/25, шт", price: 126.0, stock: 45.0, volume: "1 л", category: "home", diameter: "" },
  { name: "Щепа для копчения \"Яблоня\" 1л, BOYSCOUT/25, шт", price: 126.0, stock: 32.0, volume: "1 л", category: "home", diameter: "" },
  { name: "Щётка деревянная 18 см двухстороняя с пемзой \"Банные штучки\", шт", price: 115.5, stock: 2.0, volume: "---", category: "home", diameter: "" },
  { name: "Ящик 640*170*120 терракот ДЕКОР/30, шт", price: 141.8, stock: 47.0, volume: "---", category: "home", diameter: "" },
  { name: "Ящик для овощей 36л (600*400*190), шт", price: 404.3, stock: 38.0, volume: "36 л", category: "home", diameter: "" },
  { name: "Ящик для овощей 45л (510*345*300), шт", price: 399.0, stock: 12.0, volume: "45 л", category: "home", diameter: "" },
  { name: "Ящик для овощей 45л сп/дно  (510*345*300), шт", price: 367.5, stock: 7.0, volume: "45 л", category: "home", diameter: "" },
  { name: "Ящик почтовый, шт", price: 241.5, stock: 1.0, volume: "---", category: "home", diameter: "" },
  { name: "Ящик универсальный 10 л (600*240*85)  (АП 128)/30, шт", price: 120.8, stock: 27.0, volume: "10 л", category: "home", diameter: "" },
  { name: "Ящик универсальный 3,0 л (235*235*70) (АП 114)/60, шт", price: 52.5, stock: 48.0, volume: "3.0 л", category: "home", diameter: "" },
  { name: "Ящик универсальный 7,5 л, (530*215*72) (АП683)/35, шт", price: 94.5, stock: 75.0, volume: "7.5 л", category: "home", diameter: "" },
  { name: "Ящик универсальный 8,0 л (480*200*110) (АП 111)/35, шт", price: 94.5, stock: 48.0, volume: "8.0 л", category: "home", diameter: "" },
  { name: "Ящик универсальный 8,5 л (450*250*100) (АП 105)/30, шт", price: 120.8, stock: 19.0, volume: "8.5 л", category: "home", diameter: "" },
  { name: "Ящик универсальный 9 л (650*235*75) (АП 115)/25, шт", price: 131.3, stock: 56.0, volume: "9 л", category: "home", diameter: "" },
];
// PRODUCTS_END
        // Функция для отображения товаров
        function displayProducts(productsArray) {
            const grid = document.getElementById('catalogGrid');
            if (!grid) return;

            if (productsArray.length === 0) {
                grid.innerHTML = '<p style="text-align: center; grid-column: 1/-1;">Товары не найдены</p>';
                return;
            }

            grid.innerHTML = productsArray.map(product => {
                // Определяем русское название категории для отображения
                let categoryName = '';
                switch (product.category) {
                    case 'banks': categoryName = 'Банки'; break;
                    case 'bottles': categoryName = 'Бутылки'; break;
                    case 'carboys': categoryName = 'Бутыли'; break;
                    case 'lids': categoryName = 'Крышки'; break;
                    case 'containers': categoryName = 'Ёмкости'; break;
                    case 'agriculture': categoryName = 'Агротовары'; break;
                    case 'home': categoryName = 'Для дома и дачи'; break;
                    case 'tools': categoryName = 'Инструменты'; break;
                    default: categoryName = product.category || '';
                }

                // Формируем строку с объёмом и диаметром
                let details = '';
                if (product.volume && product.volume !== '—') {
                    details += `Объём: ${product.volume}`;
                }
                if (product.diameter) {
                    if (details) details += ' | ';
                    details += `Диаметр: ${product.diameter}`;
                }
                if (product.unit && product.unit !== '—') {
                    if (details) details += ' | ';
                    details += `Ед.: ${product.unit}`;
                }

                return `
                    <div class="product-card">
                        <div class="product-info">
                            <div class="product-title">${product.name}</div>
                            <div style="font-size: 0.8rem; color: #e67e22; margin-bottom: 0.5rem;">${categoryName}</div>
                            <div class="product-details">${details || '—'}</div>
                            <div class="product-price">${product.price.toFixed(2).replace('.', ',')} ₽</div>
                            <div class="product-stock">В наличии: ${product.stock.toLocaleString('ru-RU')} шт</div>
                        </div>
                    </div>
                `;
            }).join('');
        }

        // Фильтрация по поисковому запросу
        function filterProducts(searchText) {
            if (!searchText) return products;
            const lowerSearch = searchText.toLowerCase();
            return products.filter(product =>
                product.name.toLowerCase().includes(lowerSearch)
            );
        }

        // Инициализация страницы каталога
        document.addEventListener('DOMContentLoaded', () => {
            const searchInput = document.getElementById('searchInput');
            if (searchInput) {
                // Показываем все товары при загрузке
                displayProducts(products);

                // Обработчик ввода
                searchInput.addEventListener('input', (e) => {
                    const filtered = filterProducts(e.target.value);
                    displayProducts(filtered);
                });
            }
        });